// enterpriseConstants.jsx

export const ENTERPRISE_CREATE_REQUEST = 'ENTERPRISE_CREATE_REQUEST';
export const ENTERPRISE_CREATE_SUCCESS = 'ENTERPRISE_CREATE_SUCCESS';
export const ENTERPRISE_CREATE_FAIL = 'ENTERPRISE_CREATE_FAIL';
